---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-release
  - name: bosh-release-without-registry
    optional: true
  - name: bosh-cpi-dev-artifacts
  - name: version-semver
  - name: stemcell-director
  - name: terraform-cpi
  - name: bosh-deployment
outputs:
  - name: bosh-director-deployment
  - name: terraform-cpi-deploy
run:
  path: bosh-cpi-src-in/ci/tasks/deploy-dynamic-networking.sh
params:
  bosh_vcap_password:                  ""
  director_ca:                         ""
  director_ca_private_key:             ""
  openstack_flavor:                    ""
  openstack_connection_timeout:        ""
  openstack_read_timeout:              ""
  openstack_write_timeout:             ""
  openstack_state_timeout:             ""
  private_key_data:                    ""
  bosh_registry_port:                  ""
  bosh_openstack_ca_cert:              replace-me
  openstack_auth_url:                  ""
  openstack_username:                  ""
  openstack_api_key:                   ""
  openstack_domain:                    ""
  time_server_1:                       ""
  time_server_2:                       ""
  DEBUG_BATS:                          ""
  distro:                              ""
  availability_zone:                   replace-me
